# Generated by Django 4.2.4 on 2023-09-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('lastgame', models.FloatField(default=0.0, null=True)),
                ('current_score', models.FloatField(default=0.0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='game_data_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='game_data_users_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
